#!/usr/bin/bash
# Run bash script
cat 10-top_score.sql |  sudo mysql -u root -p hbtn_0c_0
cat 13-change_class.sql  |  sudo mysql -u root -p hbtn_0c_0 
cat 10-top_score.sql |  sudo mysql -u root -p hbtn_0c_0