#!/usr/bin/bash
# Run bash script
cat 4-never_empty.sql | sudo mysql -u root -p hbtn_0d_2 
echo 'INSERT INTO id_not_null (id, name) VALUES (89, "Best School");' | sudo mysql -u root -p hbtn_0d_2 
echo 'SELECT * FROM id_not_null;' | sudo mysql -u root -p hbtn_0d_2 
echo 'INSERT INTO id_not_null (name) VALUES ("Best");' | sudo mysql -u root -p hbtn_0d_2 
echo 'SELECT * FROM id_not_null;' | sudo mysql -u root -p hbtn_0d_2
