#!/usr/bin/bash
# Run bash script
cat 7-cities.sql  | sudo mysql -u root -p
echo 'INSERT INTO cities (state_id, name) VALUES (1, "San Francisco");'  | sudo mysql -u root -p hbtn_0d_usa
echo 'SELECT * FROM cities;'  | sudo mysql -u root -p hbtn_0d_usa
echo 'INSERT INTO cities (state_id, name) VALUES (10, "Paris");'  | sudo mysql -u root -p hbtn_0d_usa
echo 'SELECT * FROM cities;'  | sudo mysql -u root -p hbtn_0d_usa