#!/usr/bin/bash
# Run bash script
echo 'SELECT * FROM states;' | sudo mysql -u root -p hbtn_0d_usa
echo 'SELECT * FROM cities;' | sudo mysql -u root -p hbtn_0d_usa
cat 8-cities_of_california_subquery.sql | sudo mysql -u root -p hbtn_0d_usa